version: '2'

networks:
  default:
    external:
      name: ca_org2

services:
  peer2-org2:
      container_name: peer2-org2
      image: hyperledger/fabric-peer
      environment:
        - CORE_PEER_ID=peer2-org2
        - CORE_PEER_ADDRESS=peer2-org2:7051
        - CORE_PEER_LOCALMSPID=org2MSP
        - CORE_PEER_MSPCONFIGPATH=/tmp/hyperledger/org2/peer2/msp
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_fabric-ca
        - CORE_LOGGING_LEVEL=DEBUG
        # - CORE_PEER_TLS_ENABLED=true
        # - CORE_PEER_TLS_CERT_FILE=/tmp/hyperledger/org2/peer2/tls-msp/signcerts/cert.pem
        # - CORE_PEER_TLS_KEY_FILE=/tmp/hyperledger/org2/peer2/tls-msp/keystore/key.pem
        # - CORE_PEER_TLS_ROOTCERT_FILE=/tmp/hyperledger/org2/peer2/tls-msp/tlscacerts/tls-0-0-0-0-7054.pem
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org2:7051
        - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-org2:7051
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/org2/peer2
      volumes:
        - ./msp:/tmp/hyperledger/org2/peer2/msp
        - ./tls-msp:/tmp/hyperledger/org2/peer2/tls-msp
        - ./assets:/tmp/hyperledger/org2/peer2/assets
        - ./admin:/tmp/hyperledger/org2/peer2/admin
