version: '2'

networks:
  org0:

services:
  rca-org0:
    container_name: rca-org0
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b rca-org0-admin:rca-org0-adminpw --port 7056'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org0,0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./ca-server:/tmp/hyperledger/fabric-ca
    networks:
      - org0
    ports:
      - 7056:7056
